USERNAME = 'XXXXXXXX'
PASSWORD = 'XXXXXXXX'
ID = 'XXXXXXXX'
SECRET_SERVER_PWD = "XXXXXXXX"
SECRET_SERVER_DB = "XXXXXXXX"

DELPHIXURL = 'XXXXXXXX'
UNIWEBURL = 'XXXXXXXX'
TSSURL    = 'XXXXXXXX'

TARGET_DB = "XXXXXXXX"
SOURCE_DB = "XXXXXXXX"


CS_OR_HR_SELECT = 'XXXXXXXX'

APP_DB = 'XXXXX'
DEV_DB = 'XXXXX'
APPSERVER_STOP_SCRIPT = 'XXX'
CHANGE_PASSWORD_SCRIPT = 'XXXX'
NEW_SYSADM_PWD = 'XXXXX'
APPSERVER_START_SCRIPT = 'XXXXX'

SQL_PLUS_USERNAME_PASSWORD = 'XXXXX'
SQL_PLUS_SCRIPT_PATH = "XXXXX"
